-- 020: coaster stats from Captain Coaster's public pages.
-- Generated by tools/cc-stats.mjs on 2026-09-21.
-- COALESCE on every column: fills a blank, never overwrites a number somebody
-- typed. Matched on name + park, the visible things, so a second run is a no-op
-- and a row that has since been renamed is simply not touched.
-- Height and length in feet, speed in mph, converted from their metric integers.

