-- 020: coaster stats and manufacturers from a Wikidata export (tools/wikidata-coasters.csv,
-- pulled by Carter from query.wikidata.org on 2026-09-21). Two sections, so either can be
-- pasted alone. COALESCE on every column: fills a blank, never overwrites. Matched on
-- name + park. Height/length converted from metres to feet, speed from m/s to mph, rounded.
-- Manufacturers are mapped from Wikidata legal names to the spellings /edit already uses.

-- ---- A. numbers: height, speed, length, opening year, steel/wood (92 rows) ----
UPDATE coasters SET h = COALESCE(h, 69) WHERE name = 'Fiorano GT Challenge (Left)' AND park = 'Ferrari World';
UPDATE coasters SET h = COALESCE(h, 64) WHERE name = 'F.L.Y.' AND park = 'Phantasialand';
UPDATE coasters SET yr = COALESCE(yr, 1979), type = COALESCE(type, 'Steel') WHERE name = 'Wilderness Run' AND park = 'Carowinds';
UPDATE coasters SET yr = COALESCE(yr, 1979), type = COALESCE(type, 'Steel') WHERE name = 'Wilderness Run' AND park = 'Cedar Point';
UPDATE coasters SET yr = COALESCE(yr, 2019) WHERE name = 'Dragonflier' AND park = 'Dollywood';
UPDATE coasters SET yr = COALESCE(yr, 2014) WHERE name = 'FireChaser Express' AND park = 'Dollywood';
UPDATE coasters SET l = COALESCE(l, 3800), yr = COALESCE(yr, 2016) WHERE name = 'Lightning Rod' AND park = 'Dollywood';
UPDATE coasters SET yr = COALESCE(yr, 2007) WHERE name = 'Mystery Mine' AND park = 'Dollywood';
UPDATE coasters SET yr = COALESCE(yr, 1999) WHERE name = 'Tennessee Tornado' AND park = 'Dollywood';
UPDATE coasters SET yr = COALESCE(yr, 2012) WHERE name = 'Wild Eagle' AND park = 'Dollywood';
UPDATE coasters SET s = COALESCE(s, 34), l = COALESCE(l, 1296) WHERE name = 'Freedom Flyer' AND park = 'Fun Spot America - Orlando';
UPDATE coasters SET type = COALESCE(type, 'Wood') WHERE name = 'White Lightning' AND park = 'Fun Spot America - Orlando';
UPDATE coasters SET l = COALESCE(l, 770), yr = COALESCE(yr, 2022) WHERE name = 'Tumbili' AND park = 'Kings Dominion';
UPDATE coasters SET yr = COALESCE(yr, 2016) WHERE name = 'Mako' AND park = 'SeaWorld Orlando';
UPDATE coasters SET yr = COALESCE(yr, 2009) WHERE name = 'Manta' AND park = 'SeaWorld Orlando';
UPDATE coasters SET yr = COALESCE(yr, 2021) WHERE name = 'Stunt Pilot' AND park = 'Silverwood Theme Park';
UPDATE coasters SET h = COALESCE(h, 62), s = COALESCE(s, 35), l = COALESCE(l, 360), yr = COALESCE(yr, 2018) WHERE name = 'Harley Quinn Crazy Coaster' AND park = 'Six Flags Discovery Kingdom';
UPDATE coasters SET yr = COALESCE(yr, 2021) WHERE name = 'Jersey Devil Coaster' AND park = 'Six Flags Great Adventure';
UPDATE coasters SET yr = COALESCE(yr, 2013) WHERE name = 'Joker' AND park = 'Six Flags Mexico';
UPDATE coasters SET yr = COALESCE(yr, 2002) WHERE name = 'Primeval Whirl (Left)' AND park = 'Disney''s Animal Kingdom';
UPDATE coasters SET yr = COALESCE(yr, 2002) WHERE name = 'Primeval Whirl (Right)' AND park = 'Disney''s Animal Kingdom';
UPDATE coasters SET yr = COALESCE(yr, 2018) WHERE name = 'Slinky Dog Dash' AND park = 'Disney''s Hollywood Studios';
UPDATE coasters SET yr = COALESCE(yr, 1993) WHERE name = 'Cosmic Coaster' AND park = 'Worlds of Fun';
UPDATE coasters SET l = COALESCE(l, 2260), yr = COALESCE(yr, 2004) WHERE name = 'Gauntlet' AND park = 'Magic Springs Theme and Water Park';
UPDATE coasters SET h = COALESCE(h, 109), yr = COALESCE(yr, 1998) WHERE name = 'Blue Tornado' AND park = 'Gardaland';
UPDATE coasters SET h = COALESCE(h, 46) WHERE name = 'Mammut' AND park = 'Gardaland';
UPDATE coasters SET h = COALESCE(h, 139), yr = COALESCE(yr, 2015) WHERE name = 'Oblivion the Black Hole' AND park = 'Gardaland';
UPDATE coasters SET h = COALESCE(h, 108), yr = COALESCE(yr, 2011) WHERE name = 'Raptor' AND park = 'Gardaland';
UPDATE coasters SET h = COALESCE(h, 98) WHERE name = 'Shaman' AND park = 'Gardaland';
UPDATE coasters SET yr = COALESCE(yr, 1986) WHERE name = 'Silver Bullet' AND park = 'Frontier City';
UPDATE coasters SET yr = COALESCE(yr, 1991) WHERE name = 'Wildcat' AND park = 'Frontier City';
UPDATE coasters SET yr = COALESCE(yr, 2019) WHERE name = 'Steel Curtain' AND park = 'Kennywood';
UPDATE coasters SET yr = COALESCE(yr, 2023) WHERE name = 'Matugani' AND park = 'Lost Island Theme Park';
UPDATE coasters SET yr = COALESCE(yr, 2025) WHERE name = 'Fire Runner' AND park = 'Lost Island Theme Park';
UPDATE coasters SET h = COALESCE(h, 213), l = COALESCE(l, 3179) WHERE name = 'Diving Coaster' AND park = 'Happy Valley';
UPDATE coasters SET yr = COALESCE(yr, 2003) WHERE name = 'Azteka (2021-)' AND park = 'Le Pal';
UPDATE coasters SET l = COALESCE(l, 1181), yr = COALESCE(yr, 1990) WHERE name = 'Tigre de Sibérie' AND park = 'Le Pal';
UPDATE coasters SET h = COALESCE(h, 39), s = COALESCE(s, 56), l = COALESCE(l, 3281) WHERE name = 'Yukon Quad' AND park = 'Le Pal';
UPDATE coasters SET yr = COALESCE(yr, 2024) WHERE name = 'Mahuka' AND park = 'Walibi Rhône-Alpes';
UPDATE coasters SET h = COALESCE(h, 102), l = COALESCE(l, 1886), yr = COALESCE(yr, 2019) WHERE name = 'Mystic' AND park = 'Walibi Rhône-Alpes';
UPDATE coasters SET yr = COALESCE(yr, 1989) WHERE name = 'Anaconda' AND park = 'Walygator Grand Est';
UPDATE coasters SET h = COALESCE(h, 52), s = COALESCE(s, 37), l = COALESCE(l, 1575), yr = COALESCE(yr, 1998) WHERE name = 'G''sengte Sau' AND park = 'Erlebnispark Tripsdrill';
UPDATE coasters SET h = COALESCE(h, 98), s = COALESCE(s, 62), l = COALESCE(l, 2297), yr = COALESCE(yr, 2013) WHERE name = 'Karacho' AND park = 'Erlebnispark Tripsdrill';
UPDATE coasters SET h = COALESCE(h, 26), s = COALESCE(s, 22), l = COALESCE(l, 1181), yr = COALESCE(yr, 1986) WHERE name = 'Rasender Tausendfüßler' AND park = 'Erlebnispark Tripsdrill';
UPDATE coasters SET h = COALESCE(h, 20), s = COALESCE(s, 28), l = COALESCE(l, 866), yr = COALESCE(yr, 1984) WHERE name = 'Alpenexpress Enzian' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 44), s = COALESCE(s, 19), l = COALESCE(l, 1657), yr = COALESCE(yr, 2014) WHERE name = 'Arthur' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 98), s = COALESCE(s, 50), l = COALESCE(l, 1280), yr = COALESCE(yr, 2005) WHERE name = 'Atlantica SuperSplash' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 10), s = COALESCE(s, 14), l = COALESCE(l, 220), yr = COALESCE(yr, 2016) WHERE name = 'Ba-a-a-Express' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 125), s = COALESCE(s, 62), l = COALESCE(l, 3465), yr = COALESCE(yr, 2009) WHERE name = 'blue fire Megacoaster' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 92), s = COALESCE(s, 50), l = COALESCE(l, 3215), yr = COALESCE(yr, 1997) WHERE name = 'Euro Mir' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 84), s = COALESCE(s, 37), l = COALESCE(l, 2953), yr = COALESCE(yr, 2018) WHERE name = 'Eurosat - CanCan Coaster' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 52), s = COALESCE(s, 35), l = COALESCE(l, 1257) WHERE name = 'Matterhorn Blitz' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 75), s = COALESCE(s, 43), l = COALESCE(l, 2743) WHERE name = 'Poseidon' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 240), s = COALESCE(s, 79), l = COALESCE(l, 5315) WHERE name = 'Silver Star' AND park = 'Europa Park';
UPDATE coasters SET h = COALESCE(h, 174), s = COALESCE(s, 75), l = COALESCE(l, 4003), yr = COALESCE(yr, 2001) WHERE name = 'Expedition GeForce' AND park = 'Plopsaland Deutschland';
UPDATE coasters SET h = COALESCE(h, 148), s = COALESCE(s, 62), l = COALESCE(l, 863), yr = COALESCE(yr, 2014) WHERE name = 'Sky Scream' AND park = 'Plopsaland Deutschland';
UPDATE coasters SET h = COALESCE(h, 30), s = COALESCE(s, 24), l = COALESCE(l, 728), yr = COALESCE(yr, 2018) WHERE name = 'Tabalugas Achterbahn' AND park = 'Plopsaland Deutschland';
UPDATE coasters SET h = COALESCE(h, 253), l = COALESCE(l, 4757), yr = COALESCE(yr, 2018) WHERE name = 'Hyperion' AND park = 'Energylandia';
UPDATE coasters SET h = COALESCE(h, 367), s = COALESCE(s, 112), l = COALESCE(l, 2887), yr = COALESCE(yr, 2017) WHERE name = 'Red Force' AND park = 'Ferrari Land';
UPDATE coasters SET yr = COALESCE(yr, 2006) WHERE name = 'Abismo' AND park = 'Parque de Atracciones de Madrid';
UPDATE coasters SET yr = COALESCE(yr, 2023) WHERE name = 'Batman Gotham City Escape' AND park = 'Parque Warner Madrid';
UPDATE coasters SET yr = COALESCE(yr, 2009) WHERE name = 'Insane' AND park = 'Gröna Lund';
UPDATE coasters SET yr = COALESCE(yr, 1988) WHERE name = 'Jetline' AND park = 'Gröna Lund';
UPDATE coasters SET yr = COALESCE(yr, 2007) WHERE name = 'Kvasten' AND park = 'Gröna Lund';
UPDATE coasters SET yr = COALESCE(yr, 2011) WHERE name = 'Twister' AND park = 'Gröna Lund';
UPDATE coasters SET yr = COALESCE(yr, 2003) WHERE name = 'Vilda Musen' AND park = 'Gröna Lund';
UPDATE coasters SET yr = COALESCE(yr, 2003) WHERE name = 'Balder' AND park = 'Liseberg';
UPDATE coasters SET h = COALESCE(h, 135), s = COALESCE(s, 62), l = COALESCE(l, 4531), yr = COALESCE(yr, 2014) WHERE name = 'Helix' AND park = 'Liseberg';
UPDATE coasters SET yr = COALESCE(yr, 1987) WHERE name = 'Lisebergbanan' AND park = 'Liseberg';
UPDATE coasters SET yr = COALESCE(yr, 2009) WHERE name = 'Rabalder' AND park = 'Liseberg';
UPDATE coasters SET yr = COALESCE(yr, 2015) WHERE name = 'Octonauts Rollercoaster Adventure' AND park = 'Alton Towers';
UPDATE coasters SET h = COALESCE(h, 69), s = COALESCE(s, 61), l = COALESCE(l, 2100), yr = COALESCE(yr, 2005) WHERE name = 'Rita' AND park = 'Alton Towers';
UPDATE coasters SET yr = COALESCE(yr, 2004) WHERE name = 'Dragon''s Fury' AND park = 'Chessington World of Adventures';
UPDATE coasters SET h = COALESCE(h, 66), s = COALESCE(s, 45), l = COALESCE(l, 1247) WHERE name = 'Mandrill Mayhem' AND park = 'Chessington World of Adventures';
UPDATE coasters SET h = COALESCE(h, 213), s = COALESCE(s, 74), l = COALESCE(l, 5497), yr = COALESCE(yr, 1994) WHERE name = 'Big One' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET yr = COALESCE(yr, 2025) WHERE name = 'Siren''s Curse' AND park = 'Cedar Point';
UPDATE coasters SET l = COALESCE(l, 3800), yr = COALESCE(yr, 2016) WHERE name = 'Lightning Rod (-2020)' AND park = 'Dollywood';
UPDATE coasters SET yr = COALESCE(yr, 2007) WHERE name = 'Mystery Mine (-2020)' AND park = 'Dollywood';
UPDATE coasters SET h = COALESCE(h, 77), l = COALESCE(l, 722), yr = COALESCE(yr, 2024) WHERE name = 'Good Gravy!' AND park = 'Holiday World';
UPDATE coasters SET h = COALESCE(h, 224), s = COALESCE(s, 70), l = COALESCE(l, 1365), yr = COALESCE(yr, 2000) WHERE name = 'Speed - The Ride' AND park = 'Nascar Café';
UPDATE coasters SET l = COALESCE(l, 2501), yr = COALESCE(yr, 2022) WHERE name = 'Dr. Diabolical''s Cliffhanger' AND park = 'Six Flags Fiesta Texas';
UPDATE coasters SET h = COALESCE(h, 133), s = COALESCE(s, 62), yr = COALESCE(yr, 2025) WHERE name = 'Stardust Racers (Photon/Yellow)' AND park = 'Universal Epic Universe';
UPDATE coasters SET h = COALESCE(h, 133), s = COALESCE(s, 62), yr = COALESCE(yr, 2025) WHERE name = 'Stardust Racers (Pulsar/Green)' AND park = 'Universal Epic Universe';
UPDATE coasters SET yr = COALESCE(yr, 2022) WHERE name = 'Guardians of the Galaxy: Cosmic Rewind' AND park = 'EPCOT';
UPDATE coasters SET yr = COALESCE(yr, 2000) WHERE name = 'Boomerang' AND park = 'Worlds of Fun';
UPDATE coasters SET yr = COALESCE(yr, 2025) WHERE name = 'Big Bad Wolf: The Wolf''s Revenge' AND park = 'Busch Gardens Williamsburg';
UPDATE coasters SET h = COALESCE(h, 148), l = COALESCE(l, 4216) WHERE name = 'Dragon Khan' AND park = 'PortAventura Park';
UPDATE coasters SET h = COALESCE(h, 72), s = COALESCE(s, 40), l = COALESCE(l, 3953), yr = COALESCE(yr, 1992) WHERE name = 'Big Thunder Mountain' AND park = 'Disneyland Park (Paris)';
UPDATE coasters SET h = COALESCE(h, 10), s = COALESCE(s, 28), l = COALESCE(l, 984), yr = COALESCE(yr, 1994) WHERE name = 'Casey Jr., Le Petit Train du Cirque' AND park = 'Disneyland Park (Paris)';
UPDATE coasters SET h = COALESCE(h, 59), s = COALESCE(s, 36), l = COALESCE(l, 1969), yr = COALESCE(yr, 1993) WHERE name = 'Indiana Jones et le Temple du Peril' AND park = 'Disneyland Park (Paris)';
UPDATE coasters SET h = COALESCE(h, 51), s = COALESCE(s, 37), l = COALESCE(l, 1788), yr = COALESCE(yr, 2007) WHERE name = 'Crush''s Coaster' AND park = 'Walt Disney Studios Park';
UPDATE coasters SET h = COALESCE(h, 218), s = COALESCE(s, 78), l = COALESCE(l, 7032) WHERE name = 'Son Of Beast' AND park = 'Kings Island';

-- ---- B. manufacturer (170 rows) ----
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Air Grover' AND park = 'Busch Gardens Tampa Bay';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Montu' AND park = 'Busch Gardens Tampa Bay';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Sand Serpent' AND park = 'Busch Gardens Tampa Bay';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'SheiKra' AND park = 'Busch Gardens Tampa Bay';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Nighthawk' AND park = 'Carowinds';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Vortex' AND park = 'Carowinds';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Wilderness Run' AND park = 'Carowinds';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Wilderness Run' AND park = 'Cedar Point';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Dragonflier' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'FireChaser Express' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Rocky Mountain Construction') WHERE name = 'Lightning Rod' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Mystery Mine' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Tennessee Tornado' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Great Coasters International') WHERE name = 'Thunderhead' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Wild Eagle' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Philadelphia Toboggan Coasters') WHERE name = 'Swamp Fox' AND park = 'Family Kingdom Amusement Park';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Sea Serpent' AND park = 'Fun Spot America - Kissimmee';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Freedom Flyer' AND park = 'Fun Spot America - Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Sea Serpent' AND park = 'Fun Spot America - Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Great Coasters International') WHERE name = 'White Lightning' AND park = 'Fun Spot America - Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Iron Shark' AND park = 'Galveston Island Historic Pleasure Pier';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Cornball Express' AND park = 'Indiana Beach';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Hoosier Hurricane' AND park = 'Indiana Beach';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Lost Coaster of Superstition Mountain' AND park = 'Indiana Beach';
UPDATE coasters SET manu = COALESCE(manu, 'S&S Worldwide') WHERE name = 'Steel Hawg' AND park = 'Indiana Beach';
UPDATE coasters SET manu = COALESCE(manu, 'Martin & Vleminckx') WHERE name = 'Boardwalk Bullet' AND park = 'Kemah Boardwalk';
UPDATE coasters SET manu = COALESCE(manu, 'S&S Worldwide') WHERE name = 'Tumbili' AND park = 'Kings Dominion';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Sandy''s Blasting Bronco' AND park = 'Nickelodeon Universe Theme Park';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Mako' AND park = 'SeaWorld Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Manta' AND park = 'SeaWorld Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Rocky Mountain Construction') WHERE name = 'Stunt Pilot' AND park = 'Silverwood Theme Park';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Timber Terror' AND park = 'Silverwood Theme Park';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Tremors' AND park = 'Silverwood Theme Park';
UPDATE coasters SET manu = COALESCE(manu, 'Skyline Attractions') WHERE name = 'Harley Quinn Crazy Coaster' AND park = 'Six Flags Discovery Kingdom';
UPDATE coasters SET manu = COALESCE(manu, 'Rocky Mountain Construction') WHERE name = 'Jersey Devil Coaster' AND park = 'Six Flags Great Adventure';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Joker' AND park = 'Six Flags Mexico';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Blue Hawk' AND park = 'Six Flags Over Georgia';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Dare Devil Dive' AND park = 'Six Flags Over Georgia';
UPDATE coasters SET manu = COALESCE(manu, 'Rocky Mountain Construction') WHERE name = 'Twisted Cyclone' AND park = 'Six Flags Over Georgia';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'Hollywood Rip Ride Rockit' AND park = 'Universal Studios Florida';
UPDATE coasters SET manu = COALESCE(manu, 'Reverchon') WHERE name = 'Primeval Whirl (Left)' AND park = 'Disney''s Animal Kingdom';
UPDATE coasters SET manu = COALESCE(manu, 'Reverchon') WHERE name = 'Primeval Whirl (Right)' AND park = 'Disney''s Animal Kingdom';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Slinky Dog Dash' AND park = 'Disney''s Hollywood Studios';
UPDATE coasters SET manu = COALESCE(manu, 'Dynamic Attractions') WHERE name = 'Space Mountain (Alpha)' AND park = 'Magic Kingdom';
UPDATE coasters SET manu = COALESCE(manu, 'Great Coasters International') WHERE name = 'Ozark Wildcat' AND park = 'Celebration City';
UPDATE coasters SET manu = COALESCE(manu, 'Preston & Barbieri') WHERE name = 'Cosmic Coaster' AND park = 'Worlds of Fun';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Gauntlet' AND park = 'Magic Springs Theme and Water Park';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Blue Tornado' AND park = 'Gardaland';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Mammut' AND park = 'Gardaland';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Oblivion the Black Hole' AND park = 'Gardaland';
UPDATE coasters SET manu = COALESCE(manu, 'Pinfari') WHERE name = 'Ortobruco Tour' AND park = 'Gardaland';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Raptor' AND park = 'Gardaland';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Shaman' AND park = 'Gardaland';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Seven Dwarfs Mine Train' AND park = 'Magic Kingdom';
UPDATE coasters SET manu = COALESCE(manu, 'Chance Rides') WHERE name = 'Wile E Coyote''s Grand Canyon Blaster' AND park = 'Six Flags Over Texas';
UPDATE coasters SET manu = COALESCE(manu, 'Schwarzkopf') WHERE name = 'Silver Bullet' AND park = 'Frontier City';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Steel Lasso' AND park = 'Frontier City';
UPDATE coasters SET manu = COALESCE(manu, 'National Amusement Devices') WHERE name = 'Wildcat' AND park = 'Frontier City';
UPDATE coasters SET manu = COALESCE(manu, 'Allan Herschell') WHERE name = 'Wild Kitty' AND park = 'Frontier City';
UPDATE coasters SET manu = COALESCE(manu, 'Zamperla') WHERE name = 'Opa' AND park = 'Mt. Olympus';
UPDATE coasters SET manu = COALESCE(manu, 'S&S Worldwide') WHERE name = 'Steel Curtain' AND park = 'Kennywood';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Firehawk' AND park = 'Kings Island';
UPDATE coasters SET manu = COALESCE(manu, 'Great Coasters International') WHERE name = 'Texas Stingray' AND park = 'SeaWorld San Antonio';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Zach''s Zoomer' AND park = 'Michigan''s Adventure';
UPDATE coasters SET manu = COALESCE(manu, 'Dinn Corporation') WHERE name = 'Wolverine Wildcat' AND park = 'Michigan''s Adventure';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Shivering Timbers' AND park = 'Michigan''s Adventure';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Dahlonega Mine Train' AND park = 'Six Flags Over Georgia';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Georgia Scorcher' AND park = 'Six Flags Over Georgia';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Matugani' AND park = 'Lost Island Theme Park';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Diving Coaster' AND park = 'Happy Valley';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Family Inverted Coaster' AND park = 'Happy Valley';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'TRON Lightcycle Power Run' AND park = 'Shanghai Disneyland';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Falcon' AND park = 'Wuxi Sunac Land';
UPDATE coasters SET manu = COALESCE(manu, 'Soquet') WHERE name = 'Azteka (2021-)' AND park = 'Le Pal';
UPDATE coasters SET manu = COALESCE(manu, 'Reverchon') WHERE name = 'Tigre de Sibérie' AND park = 'Le Pal';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Yukon Quad' AND park = 'Le Pal';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Mystic' AND park = 'Walibi Rhône-Alpes';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Monster' AND park = 'Walygator Grand Est';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'G''sengte Sau' AND park = 'Erlebnispark Tripsdrill';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Karacho' AND park = 'Erlebnispark Tripsdrill';
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Rasender Tausendfüßler' AND park = 'Erlebnispark Tripsdrill';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Alpenexpress Enzian' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Arthur' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Atlantica SuperSplash' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'blue fire Megacoaster' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Euro Mir' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Eurosat - CanCan Coaster' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Matterhorn Blitz' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Poseidon' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Silver Star' AND park = 'Europa Park';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Flug der Dämonen' AND park = 'Heide Park Resort';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Grottenblitz' AND park = 'Heide Park Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Krake' AND park = 'Heide Park Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Expedition GeForce' AND park = 'Plopsaland Deutschland';
UPDATE coasters SET manu = COALESCE(manu, 'Premier Rides') WHERE name = 'Sky Scream' AND park = 'Plopsaland Deutschland';
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Tabalugas Achterbahn' AND park = 'Plopsaland Deutschland';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Dragon Roller Coaster' AND park = 'Energylandia';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Hyperion' AND park = 'Energylandia';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Red Force' AND park = 'Ferrari Land';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'Abismo' AND park = 'Parque de Atracciones de Madrid';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Batman Gotham City Escape' AND park = 'Parque Warner Madrid';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Superman / la Atracción de Acero' AND park = 'Parque Warner Madrid';
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Tom y Jerry' AND park = 'Parque Warner Madrid';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Furius Baco' AND park = 'PortAventura Park';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Shambhala' AND park = 'PortAventura Park';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Muntanya Russa' AND park = 'Tibidabo';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Insane' AND park = 'Gröna Lund';
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Jetline' AND park = 'Gröna Lund';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Kvasten' AND park = 'Gröna Lund';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Vilda Musen' AND park = 'Gröna Lund';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Balder' AND park = 'Liseberg';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Helix' AND park = 'Liseberg';
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Lisebergbanan' AND park = 'Liseberg';
UPDATE coasters SET manu = COALESCE(manu, 'S&S Worldwide') WHERE name = 'Tranan' AND park = 'Skara Sommarland';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Galactica' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Oblivion' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Zamperla') WHERE name = 'Octonauts Rollercoaster Adventure' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Rita' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Runaway Mine Train' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Smiler' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'Spinball Whizzer' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Great Coasters International') WHERE name = 'Wicker Man' AND park = 'Alton Towers';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'Dragon''s Fury' AND park = 'Chessington World of Adventures';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Mandrill Mayhem' AND park = 'Chessington World of Adventures';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'Rattlesnake' AND park = 'Chessington World of Adventures';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Accelerator' AND park = 'Drayton Manor';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Big One' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Icon' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Infusion' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Steeplechase (Green)' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Steeplechase (Red)' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Steeplechase (Yellow)' AND park = 'Pleasure Beach Resort';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Galaxy Orbiter' AND park = 'Galaxyland';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Dragon Mountain' AND park = 'Marineland Theme Park';
UPDATE coasters SET manu = COALESCE(manu, 'Great Coasters International') WHERE name = 'Kentucky Rumbler' AND park = 'Beech Bend';
UPDATE coasters SET manu = COALESCE(manu, 'Arrow Dynamics') WHERE name = 'Canobie Corkscrew' AND park = 'Canobie Lake Park';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Untamed' AND park = 'Canobie Lake Park';
UPDATE coasters SET manu = COALESCE(manu, 'Philadelphia Toboggan Coasters') WHERE name = 'Yankee Cannonball' AND park = 'Canobie Lake Park';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Siren''s Curse' AND park = 'Cedar Point';
UPDATE coasters SET manu = COALESCE(manu, 'S&S Worldwide') WHERE name = 'Hell Cat' AND park = 'Clementon Park';
UPDATE coasters SET manu = COALESCE(manu, 'Philadelphia Toboggan Coasters') WHERE name = 'Sea Dragon' AND park = 'Columbus Zoo and Aquarium';
UPDATE coasters SET manu = COALESCE(manu, 'Rocky Mountain Construction') WHERE name = 'Lightning Rod (-2020)' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Mystery Mine (-2020)' AND park = 'Dollywood';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Good Gravy!' AND park = 'Holiday World';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Volcano - The Blast Coaster' AND park = 'Kings Dominion';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Zoomerang' AND park = 'Lake Compounce';
UPDATE coasters SET manu = COALESCE(manu, 'Zierer') WHERE name = 'Flitzer' AND park = 'Morey''s Piers';
UPDATE coasters SET manu = COALESCE(manu, 'Premier Rides') WHERE name = 'Speed - The Ride' AND park = 'Nascar Café';
UPDATE coasters SET manu = COALESCE(manu, 'Custom Coasters International') WHERE name = 'Silver Comet' AND park = 'Niagara Amusement Park & Splash World';
UPDATE coasters SET manu = COALESCE(manu, 'Gravity Group') WHERE name = 'Wooden Warrior' AND park = 'Quassy Amusement Park';
UPDATE coasters SET manu = COALESCE(manu, 'Premier Rides') WHERE name = 'Ice Breaker' AND park = 'SeaWorld Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Pipeline: The Surf Coaster' AND park = 'SeaWorld Orlando';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Dr. Diabolical''s Cliffhanger' AND park = 'Six Flags Fiesta Texas';
UPDATE coasters SET manu = COALESCE(manu, 'Rocky Mountain Construction') WHERE name = 'Wonder Woman Golden Lasso Coaster' AND park = 'Six Flags Fiesta Texas';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Goliath' AND park = 'Six Flags New England';
UPDATE coasters SET manu = COALESCE(manu, 'Gravity Group') WHERE name = 'Roar-O-Saurus' AND park = 'Story Land';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Stardust Racers (Photon/Yellow)' AND park = 'Universal Epic Universe';
UPDATE coasters SET manu = COALESCE(manu, 'MACK Rides') WHERE name = 'Stardust Racers (Pulsar/Green)' AND park = 'Universal Epic Universe';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Guardians of the Galaxy: Cosmic Rewind' AND park = 'EPCOT';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Boomerang' AND park = 'Worlds of Fun';
UPDATE coasters SET manu = COALESCE(manu, 'TOGO') WHERE name = 'Shockwave' AND park = 'Kings Dominion';
UPDATE coasters SET manu = COALESCE(manu, 'Bolliger & Mabillard') WHERE name = 'Dragon Khan' AND park = 'PortAventura Park';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Woody Woodpecker''s Nuthouse Coaster' AND park = 'Universal Studios Florida';
UPDATE coasters SET manu = COALESCE(manu, 'Gerstlauer') WHERE name = 'Hydrus' AND park = 'Casino Pier';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Big Thunder Mountain' AND park = 'Disneyland Park (Paris)';
UPDATE coasters SET manu = COALESCE(manu, 'Vekoma') WHERE name = 'Casey Jr., Le Petit Train du Cirque' AND park = 'Disneyland Park (Paris)';
UPDATE coasters SET manu = COALESCE(manu, 'Intamin') WHERE name = 'Indiana Jones et le Temple du Peril' AND park = 'Disneyland Park (Paris)';
UPDATE coasters SET manu = COALESCE(manu, 'Maurer Rides') WHERE name = 'Crush''s Coaster' AND park = 'Walt Disney Studios Park';
UPDATE coasters SET manu = COALESCE(manu, 'Caripro') WHERE name = 'Scooby''s Ghoster Coaster' AND park = 'Kings Island';
UPDATE coasters SET manu = COALESCE(manu, 'Roller Coaster Corporation of America') WHERE name = 'Son Of Beast' AND park = 'Kings Island';
