-- 020: coaster stats from Captain Coaster's public pages.
-- Generated by tools/cc-stats.mjs on 2026-09-21.
-- COALESCE on every column: fills a blank, never overwrites a number somebody
-- typed. Matched on name + park, the visible things, so a second run is a no-op
-- and a row that has since been renamed is simply not touched.
-- Height and length in feet, speed in mph, converted from their metric integers.

UPDATE coasters SET type = COALESCE(type, 'Steel'), h = COALESCE(h, 233), s = COALESCE(s, 75), l = COALESCE(l, 5315), inv = COALESCE(inv, 0), yr = COALESCE(yr, 2010), opened = COALESCE(opened, '2010-03-27'), openedPrec = COALESCE(openedPrec, 'd'), manu = COALESCE(manu, 'Bolliger & Mabillard'), model = COALESCE(model, 'B&M Hyper Coaster') WHERE name = 'Thunder Striker' AND park = 'Carowinds';
UPDATE coasters SET type = COALESCE(type, 'Steel'), h = COALESCE(h, 30), s = COALESCE(s, 22), l = COALESCE(l, 679), inv = COALESCE(inv, 0), yr = COALESCE(yr, 1999), opened = COALESCE(opened, '1999-03-13'), openedPrec = COALESCE(openedPrec, 'd'), manu = COALESCE(manu, 'Vekoma'), model = COALESCE(model, 'Vekoma Junior Coaster') WHERE name = 'Trolls Trollercoaster' AND park = 'Universal Studios Florida';
UPDATE coasters SET h = COALESCE(h, 13), l = COALESCE(l, 262), inv = COALESCE(inv, 0), yr = COALESCE(yr, 2007), opened = COALESCE(opened, '2007-06-02'), openedPrec = COALESCE(openedPrec, 'd'), manu = COALESCE(manu, 'Zamperla'), model = COALESCE(model, 'Zamperla Family Coaster') WHERE name = 'Paw Patrol: Patrulla Canina' AND park = 'Parque de Atracciones de Madrid';
UPDATE coasters SET h = COALESCE(h, 43), s = COALESCE(s, 50), l = COALESCE(l, 2349), inv = COALESCE(inv, 4), yr = COALESCE(yr, 1994), opened = COALESCE(opened, '1994-03-19'), openedPrec = COALESCE(openedPrec, 'd'), manu = COALESCE(manu, 'Bolliger & Mabillard'), model = COALESCE(model, 'B&M Inverted Coaster') WHERE name = 'Nemesis Reborn' AND park = 'Alton Towers';
UPDATE coasters SET h = COALESCE(h, 36), s = COALESCE(s, 30), l = COALESCE(l, 1099), inv = COALESCE(inv, 0), yr = COALESCE(yr, 1985), opened = COALESCE(opened, '1985-01-01'), openedPrec = COALESCE(openedPrec, 'y'), manu = COALESCE(manu, 'Zierer'), model = COALESCE(model, 'Zierer Tivoli') WHERE name = 'Cootie Coaster' AND park = 'Galaxyland';
