-- 028: parks and coasters for a second rider's ranking sheet (2026-10-04).
-- Carter sent "Roller_Coaster_Ranking.xlsx" (341 ranked rides, mostly Germany,
-- Austria, Benelux, Italy, Poland and French/German travelling fairs):
-- "Another please".
--
-- Matched against the live tables after 027. Before this, 153 rows had no
-- match: 126 at 54 parks we lacked, the rest at parks we have. After it, every
-- park matches, and the 11 rows left are spellings /import already resolves
-- or asks about ("Max & Moritz (Max)", "Dawson Duel (left)" against our
-- Blue/Green, "le Twist").
--
-- Unlike 027's sheet this one carries no maker or model, so those are filled
-- only where certain (iSpeed, Katun, Star Trek, Falcon, Thundercoaster …) and
-- left blank otherwise for /edit. Same for opening years. Pins for parks with
-- a fixed address; travelling showmen as "<Name> (travelling)", as in 027.
-- Some of the sheet's park names are other names for parks we have (Kolmården
-- Zoo, Ferrari World Abu Dhabi, Plopsaland Ardennes = Plopsa Coo, plain
-- "Barth"/"Eberhard" for 027's showmen) and go in as park aliases.
--
-- Safe to run twice; the same name (+ park) checks as 027. Dry run against
-- the live tables: parks 340 -> 384, coasters 1470 -> 1593; a second run
-- changed nothing. Raw SQL skips the Worker, so run Actions -> "Sync static
-- JSON from D1" after.
--
-- From a phone, paste migrations/028-paste/part-N.sql in order.
INSERT INTO parks (name, lat, lon, region) SELECT 'Mirabilandia', 44.338, 12.263, 'Italy' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia');
INSERT INTO parks (name, lat, lon, region) SELECT 'Movie Park Germany', 51.622, 6.975, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany');
INSERT INTO parks (name, lat, lon, region) SELECT 'Attractiepark Slagharen', 52.623, 6.56, 'Netherlands' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Attractiepark Slagharen');
INSERT INTO parks (name, lat, lon, region) SELECT 'Drievliet', 52.054, 4.353, 'Netherlands' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Drievliet');
INSERT INTO parks (name, lat, lon, region) SELECT 'Duinrell', 52.146, 4.39, 'Netherlands' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Duinrell');
INSERT INTO parks (name, lat, lon, region) SELECT 'De Waarbeek', 52.244, 6.822, 'Netherlands' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'De Waarbeek');
INSERT INTO parks (name, lat, lon, region) SELECT 'SnowWorld Landgraaf', 50.894, 6.027, 'Netherlands' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'SnowWorld Landgraaf');
INSERT INTO parks (name, lat, lon, region) SELECT 'Holleshof', NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Holleshof');
INSERT INTO parks (name, lat, lon, region) SELECT 'Tivoli Friheden', 56.137, 10.2, 'Denmark' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Tivoli Friheden');
INSERT INTO parks (name, lat, lon, region) SELECT 'Legoland Billund', 55.735, 9.126, 'Denmark' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Billund');
INSERT INTO parks (name, lat, lon, region) SELECT 'Cavallino Matto', 43.128, 10.541, 'Italy' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Cavallino Matto');
INSERT INTO parks (name, lat, lon, region) SELECT 'Belantis', 51.263, 12.331, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Belantis');
INSERT INTO parks (name, lat, lon, region) SELECT 'Wiener Prater', 48.216, 16.396, 'Austria' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater');
INSERT INTO parks (name, lat, lon, region) SELECT 'Legoland Deutschland', 48.426, 10.3, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Deutschland');
INSERT INTO parks (name, lat, lon, region) SELECT 'FortFun Abenteuerland', 51.35, 8.44, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'FortFun Abenteuerland');
INSERT INTO parks (name, lat, lon, region) SELECT 'Potts Park', 52.27, 8.86, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Potts Park');
INSERT INTO parks (name, lat, lon, region) SELECT 'Schloss Beck', 51.574, 6.919, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Schloss Beck');
INSERT INTO parks (name, lat, lon, region) SELECT 'Kernie''s Familienpark', 51.58, 6.92, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Kernie''s Familienpark');
INSERT INTO parks (name, lat, lon, region) SELECT 'Freizeitsee Triolago', 49.795, 6.8, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Freizeitsee Triolago');
INSERT INTO parks (name, lat, lon, region) SELECT 'Edelwies', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Edelwies');
INSERT INTO parks (name, lat, lon, region) SELECT 'Brocken', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Brocken');
INSERT INTO parks (name, lat, lon, region) SELECT 'Familienerlebnis Drachental', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Familienerlebnis Drachental');
INSERT INTO parks (name, lat, lon, region) SELECT 'AltmühlBOB', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'AltmühlBOB');
INSERT INTO parks (name, lat, lon, region) SELECT 'Conny-Land', 47.62, 9.06, 'Switzerland' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Conny-Land');
INSERT INTO parks (name, lat, lon, region) SELECT 'Rittisberg', 47.42, 13.66, 'Austria' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Rittisberg');
INSERT INTO parks (name, lat, lon, region) SELECT 'Bergbahnen Fieberbrunn', 47.47, 12.55, 'Austria' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Bergbahnen Fieberbrunn');
INSERT INTO parks (name, lat, lon, region) SELECT 'Freizeitpark Familienland', 47.53, 12.6, 'Austria' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Freizeitpark Familienland');
INSERT INTO parks (name, lat, lon, region) SELECT 'Grünbergalm', 47.92, 13.81, 'Austria' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Grünbergalm');
INSERT INTO parks (name, lat, lon, region) SELECT 'Mandoria', 51.67, 19.49, 'Poland' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Mandoria');
INSERT INTO parks (name, lat, lon, region) SELECT 'Luna Park La Palmyre', 45.69, -1.18, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Luna Park La Palmyre');
INSERT INTO parks (name, lat, lon, region) SELECT 'Parc de la Vallée', 46.99, -0.26, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Parc de la Vallée');
INSERT INTO parks (name, lat, lon, region) SELECT 'Bauermeister (travelling)', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Bauermeister (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Wegener (travelling)', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Wegener (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Vorlop (travelling)', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Vorlop (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Schwerin (travelling)', NULL, NULL, 'Germany' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Schwerin (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Vancraeyenest (travelling)', NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Vancraeyenest (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Axels Nöjesfält (travelling)', NULL, NULL, 'Sweden' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Axels Nöjesfält (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Degousée (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Degousée (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Lapere/Ropers (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Lapere/Ropers (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Montalétang (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Montalétang (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Troisne (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Troisne (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Dugast (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Dugast (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Jacquier (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Jacquier (travelling)');
INSERT INTO parks (name, lat, lon, region) SELECT 'Kazazian (travelling)', NULL, NULL, 'France' WHERE NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Kazazian (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'iSpeed', 'Mirabilandia', 'Steel', 'Intamin', 'Intamin Launch', 1, 2009, '2009', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'iSpeed' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Katun', 'Mirabilandia', 'Steel', 'Bolliger & Mabillard', 'B&M Invert', 1, 2000, '2000', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Katun' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Desmo Race (Destra)', 'Mirabilandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Desmo Race (Destra)' AND park = 'Mirabilandia');
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Desmo Race Destra', 'import 028', date('now') FROM coasters WHERE name = 'Desmo Race (Destra)' AND park = 'Mirabilandia';
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Desmo Race (Sinistra)', 'Mirabilandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Desmo Race (Sinistra)' AND park = 'Mirabilandia');
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Desmo Race Sinistra', 'import 028', date('now') FROM coasters WHERE name = 'Desmo Race (Sinistra)' AND park = 'Mirabilandia';
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Demo Race Sinistra', 'import 028', date('now') FROM coasters WHERE name = 'Desmo Race (Sinistra)' AND park = 'Mirabilandia';
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Gold Digger', 'Mirabilandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Gold Digger' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Divertical', 'Mirabilandia', 'Steel', 'Intamin', NULL, 1, 2012, '2012', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Divertical' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Master Thai', 'Mirabilandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Master Thai' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Leprotto Express', 'Mirabilandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Leprotto Express' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Rexplorer', 'Mirabilandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mirabilandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Rexplorer' AND park = 'Mirabilandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Star Trek: Operation Enterprise', 'Movie Park Germany', 'Steel', 'MACK Rides', 'MACK Launch', 1, 2017, '2017', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Star Trek: Operation Enterprise' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Van Helsing''s Factory', 'Movie Park Germany', 'Steel', 'Gerstlauer', NULL, 1, 2011, '2011', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Van Helsing''s Factory' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Movie Park Studios Tour', 'Movie Park Germany', 'Steel', 'MACK Rides', NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Movie Park Studios Tour' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Ghost Chasers', 'Movie Park Germany', 'Steel', 'MACK Rides', NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Ghost Chasers' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Backyardigans Mission to Mars', 'Movie Park Germany', 'Steel', 'Vekoma', NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Backyardigans Mission to Mars' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'The Bandit', 'Movie Park Germany', 'Wood', NULL, 'Wood', 1, 1999, '1999', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'The Bandit' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Jimmy Neutron''s Atomic Flyer', 'Movie Park Germany', 'Steel', 'Vekoma', NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Jimmy Neutron''s Atomic Flyer' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Iron Claw', 'Movie Park Germany', 'Steel', 'Vekoma', NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Movie Park Germany') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Iron Claw' AND park = 'Movie Park Germany');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Gold Rush', 'Attractiepark Slagharen', 'Steel', 'Gerstlauer', NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Attractiepark Slagharen') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Gold Rush' AND park = 'Attractiepark Slagharen');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Mine Train', 'Attractiepark Slagharen', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Attractiepark Slagharen') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Mine Train' AND park = 'Attractiepark Slagharen');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Formule X', 'Drievliet', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Drievliet') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Formule X' AND park = 'Drievliet');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Twistrix', 'Drievliet', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Drievliet') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Twistrix' AND park = 'Drievliet');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Kopermijn', 'Drievliet', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Drievliet') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Kopermijn' AND park = 'Drievliet');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dynamite Express', 'Drievliet', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Drievliet') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dynamite Express' AND park = 'Drievliet');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Falcon', 'Duinrell', 'Steel', 'Gerstlauer', 'Gerstlauer Euro-Fighter', 1, 2009, '2009', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Duinrell') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Falcon' AND park = 'Duinrell');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Kikkerachtbaan', 'Duinrell', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Duinrell') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Kikkerachtbaan' AND park = 'Duinrell');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dragon Fly', 'Duinrell', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Duinrell') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dragon Fly' AND park = 'Duinrell');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Raptor Adventure', 'De Waarbeek', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'De Waarbeek') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Raptor Adventure' AND park = 'De Waarbeek');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Rupsje Mae', 'De Waarbeek', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'De Waarbeek') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Rupsje Mae' AND park = 'De Waarbeek');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Rodelbaan', 'De Waarbeek', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'De Waarbeek') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Rodelbaan' AND park = 'De Waarbeek');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Alpine Coaster', 'SnowWorld Landgraaf', 'Steel', NULL, 'Alpine', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'SnowWorld Landgraaf') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Alpine Coaster' AND park = 'SnowWorld Landgraaf');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Loren-Express', 'Holleshof', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Holleshof') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Loren-Express' AND park = 'Holleshof');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Vindfald', 'Tivoli Friheden', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Tivoli Friheden') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Vindfald' AND park = 'Tivoli Friheden');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dragen', 'Tivoli Friheden', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Tivoli Friheden') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dragen' AND park = 'Tivoli Friheden');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Tyfonen', 'Tivoli Friheden', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Tivoli Friheden') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Tyfonen' AND park = 'Tivoli Friheden');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Bisværmen', 'Tivoli Friheden', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Tivoli Friheden') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Bisværmen' AND park = 'Tivoli Friheden');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Polar X-plorer', 'Legoland Billund', 'Steel', 'Zierer', NULL, 1, 2012, '2012', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Billund') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Polar X-plorer' AND park = 'Legoland Billund');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'X-treme Racers', 'Legoland Billund', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Billund') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'X-treme Racers' AND park = 'Legoland Billund');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dragen', 'Legoland Billund', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Billund') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dragen' AND park = 'Legoland Billund');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Flying Eagle', 'Legoland Billund', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Billund') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Flying Eagle' AND park = 'Legoland Billund');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Freestyle', 'Cavallino Matto', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Cavallino Matto') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Freestyle' AND park = 'Cavallino Matto');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Wild Mine', 'Cavallino Matto', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Cavallino Matto') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Wild Mine' AND park = 'Cavallino Matto');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Project 1', 'Cavallino Matto', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Cavallino Matto') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Project 1' AND park = 'Cavallino Matto');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Speedy Gonzales', 'Cavallino Matto', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Cavallino Matto') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Speedy Gonzales' AND park = 'Cavallino Matto');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Topo Zorro', 'Cavallino Matto', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Cavallino Matto') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Topo Zorro' AND park = 'Cavallino Matto');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Huracan', 'Belantis', 'Steel', 'Gerstlauer', 'Gerstlauer Euro-Fighter', 1, 2010, '2010', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Belantis') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Huracan' AND park = 'Belantis');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Cobra des Amun Ra', 'Belantis', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Belantis') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Cobra des Amun Ra' AND park = 'Belantis');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Drachenritt', 'Belantis', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Belantis') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Drachenritt' AND park = 'Belantis');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Megablitz', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Megablitz' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Volare', 'Wiener Prater', 'Steel', 'Zamperla', 'Zamperla Volare', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Volare' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dizzy Mouse', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dizzy Mouse' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Insider', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Insider' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Maskerade', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Maskerade' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Boomerang', 'Wiener Prater', 'Steel', 'Vekoma', 'Vekoma Boomerang', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Boomerang' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Gesengte Sau', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Gesengte Sau' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Wilde Maus', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Wilde Maus' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Zug des Manitu', 'Wiener Prater', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wiener Prater') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Zug des Manitu' AND park = 'Wiener Prater');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Maximus - Der Flug des Wächters', 'Legoland Deutschland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Deutschland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Maximus - Der Flug des Wächters' AND park = 'Legoland Deutschland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Feuerdrache', 'Legoland Deutschland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Deutschland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Feuerdrache' AND park = 'Legoland Deutschland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Das Große LEGO Rennen', 'Legoland Deutschland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Deutschland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Das Große LEGO Rennen' AND park = 'Legoland Deutschland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Drachenjagd', 'Legoland Deutschland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Legoland Deutschland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Drachenjagd' AND park = 'Legoland Deutschland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Trapper Slider', 'FortFun Abenteuerland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'FortFun Abenteuerland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Trapper Slider' AND park = 'FortFun Abenteuerland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Devil''s Mine', 'FortFun Abenteuerland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'FortFun Abenteuerland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Devil''s Mine' AND park = 'FortFun Abenteuerland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Marienkäferbahn', 'FortFun Abenteuerland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'FortFun Abenteuerland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Marienkäferbahn' AND park = 'FortFun Abenteuerland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Speed Snake Free', 'FortFun Abenteuerland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'FortFun Abenteuerland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Speed Snake Free' AND park = 'FortFun Abenteuerland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Potts Blitz', 'Potts Park', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Potts Park') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Potts Blitz' AND park = 'Potts Park');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Turbo-Drachen', 'Potts Park', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Potts Park') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Turbo-Drachen' AND park = 'Potts Park');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Säbelsaurus', 'Potts Park', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Potts Park') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Säbelsaurus' AND park = 'Potts Park');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Familienachterbahn', 'Schloss Beck', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Schloss Beck') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Familienachterbahn' AND park = 'Schloss Beck');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Achterbahn', 'Kernie''s Familienpark', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Kernie''s Familienpark') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Achterbahn' AND park = 'Kernie''s Familienpark');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Moselbob', 'Freizeitsee Triolago', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Freizeitsee Triolago') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Moselbob' AND park = 'Freizeitsee Triolago');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Eulenblitz', 'Edelwies', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Edelwies') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Eulenblitz' AND park = 'Edelwies');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Marienkäfer', 'Edelwies', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Edelwies') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Marienkäfer' AND park = 'Edelwies');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Höllencoaster', 'Edelwies', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Edelwies') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Höllencoaster' AND park = 'Edelwies');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Brocken coaster', 'Brocken', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Brocken') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Brocken coaster' AND park = 'Brocken');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Drachenflitzer', 'Familienerlebnis Drachental', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Familienerlebnis Drachental') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Drachenflitzer' AND park = 'Familienerlebnis Drachental');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'AltmühlBOB', 'AltmühlBOB', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'AltmühlBOB') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'AltmühlBOB' AND park = 'AltmühlBOB');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Speed Bob', 'AltmühlBOB', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'AltmühlBOB') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Speed Bob' AND park = 'AltmühlBOB');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Cobra', 'Conny-Land', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Conny-Land') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Cobra' AND park = 'Conny-Land');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Rittisberg Coaster', 'Rittisberg', 'Steel', NULL, 'Alpine', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Rittisberg') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Rittisberg Coaster' AND park = 'Rittisberg');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Timoks Alm-Coaster', 'Bergbahnen Fieberbrunn', 'Steel', NULL, 'Alpine', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Bergbahnen Fieberbrunn') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Timoks Alm-Coaster' AND park = 'Bergbahnen Fieberbrunn');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Big Bang', 'Freizeitpark Familienland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Freizeitpark Familienland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Big Bang' AND park = 'Freizeitpark Familienland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Wicky', 'Freizeitpark Familienland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Freizeitpark Familienland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Wicky' AND park = 'Freizeitpark Familienland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Grünbergflitzer', 'Grünbergalm', 'Steel', NULL, 'Alpine', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Grünbergalm') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Grünbergflitzer' AND park = 'Grünbergalm');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Aquila', 'Mandoria', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mandoria') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Aquila' AND park = 'Mandoria');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Merkant', 'Mandoria', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mandoria') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Merkant' AND park = 'Mandoria');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Valtor', 'Mandoria', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mandoria') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Valtor' AND park = 'Mandoria');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Carrara', 'Mandoria', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mandoria') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Carrara' AND park = 'Mandoria');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Mroczny Dwór', 'Mandoria', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Mandoria') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Mroczny Dwór' AND park = 'Mandoria');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Toboggan', 'Luna Park La Palmyre', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Luna Park La Palmyre') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Toboggan' AND park = 'Luna Park La Palmyre');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Jet Star', 'Luna Park La Palmyre', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Luna Park La Palmyre') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Jet Star' AND park = 'Luna Park La Palmyre');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dragon', 'Luna Park La Palmyre', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Luna Park La Palmyre') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dragon' AND park = 'Luna Park La Palmyre');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Grand Canyon', 'Parc de la Vallée', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Parc de la Vallée') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Grand Canyon' AND park = 'Parc de la Vallée');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Bobsleigh', 'Parc de la Vallée', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Parc de la Vallée') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Bobsleigh' AND park = 'Parc de la Vallée');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Chenille Vallée', 'Parc de la Vallée', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Parc de la Vallée') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Chenille Vallée' AND park = 'Parc de la Vallée');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Willy der Wurm', 'Bauermeister (travelling)', 'Steel', NULL, 'Wacky Worm', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Bauermeister (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Willy der Wurm' AND park = 'Bauermeister (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Tom der Tiger', 'Wegener (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wegener (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Tom der Tiger' AND park = 'Wegener (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Rock & Roller Coaster', 'Vorlop (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Vorlop (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Rock & Roller Coaster' AND park = 'Vorlop (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Nordmann - Viking Coaster', 'Schwerin (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Schwerin (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Nordmann - Viking Coaster' AND park = 'Schwerin (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'King', 'Vancraeyenest (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Vancraeyenest (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'King' AND park = 'Vancraeyenest (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Big Apple', 'Axels Nöjesfält (travelling)', 'Steel', NULL, 'Wacky Worm', 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Axels Nöjesfält (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Big Apple' AND park = 'Axels Nöjesfält (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Crazy Mouse', 'Degousée (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Degousée (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Crazy Mouse' AND park = 'Degousée (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Tattoo', 'Lapere/Ropers (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Lapere/Ropers (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Tattoo' AND park = 'Lapere/Ropers (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Jet Star', 'Montalétang (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Montalétang (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Jet Star' AND park = 'Montalétang (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Looping Roller Coaster', 'Troisne (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Troisne (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Looping Roller Coaster' AND park = 'Troisne (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Cortina Jet', 'Dugast (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Dugast (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Cortina Jet' AND park = 'Dugast (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Speed Mouse', 'Jacquier (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Jacquier (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Speed Mouse' AND park = 'Jacquier (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'La Pomme', 'Kazazian (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Kazazian (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'La Pomme' AND park = 'Kazazian (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Abyssus', 'Energylandia', 'Steel', 'Vekoma', NULL, 1, 2021, '2021', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Energylandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Abyssus' AND park = 'Energylandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Draken', 'Energylandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Energylandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Draken' AND park = 'Energylandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Choco Chip Creek', 'Energylandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Energylandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Choco Chip Creek' AND park = 'Energylandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Honey Harbour', 'Energylandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Energylandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Honey Harbour' AND park = 'Energylandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Circus Coaster', 'Energylandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Energylandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Circus Coaster' AND park = 'Energylandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Light Explorers', 'Energylandia', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Energylandia') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Light Explorers' AND park = 'Energylandia');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Storm - The Dragon Legend', 'Tusenfryd', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Tusenfryd') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Storm - The Dragon Legend' AND park = 'Tusenfryd');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Thundercoaster', 'Tusenfryd', 'Wood', 'Vekoma', 'Wood', 1, 2001, '2001', 'year', NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Tusenfryd') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Thundercoaster' AND park = 'Tusenfryd');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Brazilian Buggies', 'Bellewaerde', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Bellewaerde') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Brazilian Buggies' AND park = 'Bellewaerde');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Dragon Rush', 'Gardaland', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Gardaland') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Dragon Rush' AND park = 'Gardaland');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Luna', 'Liseberg', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Liseberg') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Luna' AND park = 'Liseberg');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Fils du Dragon', 'Jardin d''Acclimatation', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Jardin d''Acclimatation') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Fils du Dragon' AND park = 'Jardin d''Acclimatation');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Hundeprutten', 'BonBon-Land', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'BonBon-Land') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Hundeprutten' AND park = 'BonBon-Land');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Fireline Redwood', 'Fraispertuis City', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Fraispertuis City') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Fireline Redwood' AND park = 'Fraispertuis City');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Wilde Maus', 'Barth (travelling)', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Barth (travelling)') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Wilde Maus' AND park = 'Barth (travelling)');
INSERT INTO coasters (id, name, park, type, manu, model, laps, yr, opened, openedPrec, closed, closedPrec) SELECT (SELECT COALESCE(MAX(id),0)+1 FROM coasters), 'Schtroumpfeur', 'Plopsa Coo', 'Steel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Plopsa Coo') AND NOT EXISTS (SELECT 1 FROM coasters WHERE name = 'Schtroumpfeur' AND park = 'Plopsa Coo');
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Voltron Nevera', 'import 028', date('now') FROM coasters WHERE name = 'Voltron' AND park = 'Europa Park';
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'bigFM Expedition GeForce', 'import 028', date('now') FROM coasters WHERE name = 'Expedition GeForce' AND park = 'Plopsaland Deutschland';
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Der Schwur des Kärnan', 'import 028', date('now') FROM coasters WHERE name = 'Schwur des Kärnan' AND park = 'Hansa-Park';
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'De Draak', 'import 028', date('now') FROM coasters WHERE name = 'Draak' AND park = 'Plopsaland Belgium';
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Diabelska Pętla', 'import 028', date('now') FROM coasters WHERE name = 'Diabelska Pętla / Devil''s Loop' AND park = 'Legendia';
INSERT OR IGNORE INTO coaster_aliases (coaster_id, former_name, note, added) SELECT id, 'Voglwuide Sepp', 'import 028', date('now') FROM coasters WHERE name = 'Vogulwuide Sepp' AND park = 'Rodelbahn St. Englmar';
INSERT INTO park_aliases (park, former_name) SELECT 'Kolmården', 'Kolmården Zoo' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Kolmården') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Kolmården' AND former_name = 'Kolmården Zoo') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Kolmården Zoo');
INSERT INTO park_aliases (park, former_name) SELECT 'Ferrari World', 'Ferrari World Abu Dhabi' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Ferrari World') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Ferrari World' AND former_name = 'Ferrari World Abu Dhabi') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Ferrari World Abu Dhabi');
INSERT INTO park_aliases (park, former_name) SELECT 'Bellewaerde', 'Bellewaerde Park' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Bellewaerde') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Bellewaerde' AND former_name = 'Bellewaerde Park') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Bellewaerde Park');
INSERT INTO park_aliases (park, former_name) SELECT 'Barth (travelling)', 'Barth' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Barth (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Barth (travelling)' AND former_name = 'Barth') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Barth');
INSERT INTO park_aliases (park, former_name) SELECT 'Buwalda (travelling)', 'Buwalda' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Buwalda (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Buwalda (travelling)' AND former_name = 'Buwalda') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Buwalda');
INSERT INTO park_aliases (park, former_name) SELECT 'Schneider (travelling)', 'Schneider' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Schneider (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Schneider (travelling)' AND former_name = 'Schneider') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Schneider');
INSERT INTO park_aliases (park, former_name) SELECT 'Bruch (travelling)', 'Bruch' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Bruch (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Bruch (travelling)' AND former_name = 'Bruch') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Bruch');
INSERT INTO park_aliases (park, former_name) SELECT 'Eberhard (travelling)', 'Eberhard' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Eberhard (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Eberhard (travelling)' AND former_name = 'Eberhard') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Eberhard');
INSERT INTO park_aliases (park, former_name) SELECT 'Rodelbahn St. Englmar', 'Rodel- und Freizeitparadies St. Englmar' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Rodelbahn St. Englmar') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Rodelbahn St. Englmar' AND former_name = 'Rodel- und Freizeitparadies St. Englmar') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Rodel- und Freizeitparadies St. Englmar');
INSERT INTO park_aliases (park, former_name) SELECT 'Plopsa Coo', 'Plopsaland Ardennes' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Plopsa Coo') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Plopsa Coo' AND former_name = 'Plopsaland Ardennes') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Plopsaland Ardennes');
INSERT INTO park_aliases (park, former_name) SELECT 'Attractiepark Slagharen', 'Attraciepark Slagharen' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Attractiepark Slagharen') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Attractiepark Slagharen' AND former_name = 'Attraciepark Slagharen') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Attraciepark Slagharen');
INSERT INTO park_aliases (park, former_name) SELECT 'Bauermeister (travelling)', 'Bauermeister Ingo' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Bauermeister (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Bauermeister (travelling)' AND former_name = 'Bauermeister Ingo') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Bauermeister Ingo');
INSERT INTO park_aliases (park, former_name) SELECT 'Wegener (travelling)', 'Wegener' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Wegener (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Wegener (travelling)' AND former_name = 'Wegener') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Wegener');
INSERT INTO park_aliases (park, former_name) SELECT 'Vorlop (travelling)', 'Lutz Vorlop' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Vorlop (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Vorlop (travelling)' AND former_name = 'Lutz Vorlop') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Lutz Vorlop');
INSERT INTO park_aliases (park, former_name) SELECT 'Schwerin (travelling)', 'Schwerin K.' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Schwerin (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Schwerin (travelling)' AND former_name = 'Schwerin K.') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Schwerin K.');
INSERT INTO park_aliases (park, former_name) SELECT 'Vancraeyenest (travelling)', 'Karl Vancraeyenest' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Vancraeyenest (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Vancraeyenest (travelling)' AND former_name = 'Karl Vancraeyenest') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Karl Vancraeyenest');
INSERT INTO park_aliases (park, former_name) SELECT 'Axels Nöjesfält (travelling)', 'Axels Nöjesfält' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Axels Nöjesfält (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Axels Nöjesfält (travelling)' AND former_name = 'Axels Nöjesfält') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Axels Nöjesfält');
INSERT INTO park_aliases (park, former_name) SELECT 'Degousée (travelling)', 'Degousée' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Degousée (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Degousée (travelling)' AND former_name = 'Degousée') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Degousée');
INSERT INTO park_aliases (park, former_name) SELECT 'Lapere/Ropers (travelling)', 'Lapere/Ropers' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Lapere/Ropers (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Lapere/Ropers (travelling)' AND former_name = 'Lapere/Ropers') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Lapere/Ropers');
INSERT INTO park_aliases (park, former_name) SELECT 'Montalétang (travelling)', 'James Montalétang' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Montalétang (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Montalétang (travelling)' AND former_name = 'James Montalétang') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'James Montalétang');
INSERT INTO park_aliases (park, former_name) SELECT 'Troisne (travelling)', 'Willfried Troisne' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Troisne (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Troisne (travelling)' AND former_name = 'Willfried Troisne') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Willfried Troisne');
INSERT INTO park_aliases (park, former_name) SELECT 'Dugast (travelling)', 'Noe Dugast' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Dugast (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Dugast (travelling)' AND former_name = 'Noe Dugast') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Noe Dugast');
INSERT INTO park_aliases (park, former_name) SELECT 'Jacquier (travelling)', 'Jacquier' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Jacquier (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Jacquier (travelling)' AND former_name = 'Jacquier') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Jacquier');
INSERT INTO park_aliases (park, former_name) SELECT 'Kazazian (travelling)', 'Kazazian' WHERE EXISTS (SELECT 1 FROM parks WHERE name = 'Kazazian (travelling)') AND NOT EXISTS (SELECT 1 FROM park_aliases WHERE park = 'Kazazian (travelling)' AND former_name = 'Kazazian') AND NOT EXISTS (SELECT 1 FROM parks WHERE name = 'Kazazian');
