#!/usr/bin/env node
/* Turn the repo's JSON exports into one SQL file, for filling a fresh D1.
 *
 *   node tools/staging-seed.mjs > staging-seed.sql
 *   npx wrangler d1 execute coasterhub-staging --remote --file=staging-seed.sql
 *
 * Every statement is idempotent (INSERT OR REPLACE, and rides are cleared for a
 * rider before being re-inserted), so running it twice leaves the same database
 * rather than a doubled one.
 *
 * It writes coasters, parks, riders and rides — the shared list and everybody's
 * history. It does NOT write accounts: the staging copy has no login at all
 * (DEV_AS in wrangler.staging.jsonc), so there is nothing to sign into.
 */
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const q = (v) => v === null || v === undefined || v === "" ? "NULL" : "'" + String(v).replace(/'/g, "''") + "'";
const n = (v) => v === null || v === undefined || v === "" ? "NULL" : Number(v);

const out = [];
out.push("-- Generated by tools/staging-seed.mjs. Do not edit; regenerate.");
out.push("-- Safe to run more than once.");

const coasters = JSON.parse(readFileSync(join(ROOT, "coasters.json"), "utf8"));
const list = Array.isArray(coasters) ? coasters : (coasters.coasters || []);
for (const c of list) {
  out.push("INSERT OR REPLACE INTO coasters (id,name,park,type,manu,model,h,s,l,inv,dur,laps,yr," +
    "opened,openedPrec,closed,closedPrec) VALUES (" +
    [n(c.id), q(c.name), q(c.park), q(c.type), q(c.manu), q(c.model), n(c.h), n(c.s), n(c.l),
     n(c.inv), n(c.dur), n(c.laps), n(c.yr), q(c.opened), q(c.openedPrec),
     q(c.closed), q(c.closedPrec)].join(",") + ");");
}

const parks = JSON.parse(readFileSync(join(ROOT, "parks.json"), "utf8"));
for (const [name, p] of Object.entries(parks)) {
  out.push("INSERT OR REPLACE INTO parks (name,lat,lon,region) VALUES (" +
    [q(name), n(p.lat), n(p.lon), q(p.region)].join(",") + ");");
}

// The file is named for the slug, except Carter's, which still carries the name
// the site launched under.
const RIDERS = [["crblanchard.json", "carter", "Carter"], ["cole.json", "cole", "Cole"],
                ["max.json", "max", "Max"], ["sean.json", "sean", "Sean"],
                ["keltan.json", "keltan", "Keltan"]];
let rides = 0;
for (const [file, slug, fallback] of RIDERS) {
  const p = join(ROOT, file);
  if (!existsSync(p)) continue;
  const j = JSON.parse(readFileSync(p, "utf8"));
  out.push("INSERT OR REPLACE INTO users (slug,name,mode) VALUES (" +
    [q(slug), q(j.user || fallback), "'rides'"].join(",") + ");");
  // Cleared first: rides have no natural key, so a second run would otherwise
  // give everybody twice the credits they have.
  out.push("DELETE FROM rides WHERE user_slug = " + q(slug) + ";");
  for (const r of (j.rides || [])) {
    out.push("INSERT INTO rides (user_slug,coaster_id,d) VALUES (" +
      [q(slug), n(r.c), q(r.d)].join(",") + ");");
    rides++;
  }
}

process.stdout.write(out.join("\n") + "\n");
process.stderr.write("wrote " + list.length + " coasters, " + Object.keys(parks).length +
  " parks, " + rides.toLocaleString() + " rides\n");
